[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[metadata]
name = "zoedepth"
version = "0.5"
dependencies = [
]

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters